server:
  port: 8085

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 自定义redis key
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 60 # 验证码超期时间
    common: 86400 # 24小时

# 消息队列定义
#rabbitmq:
#  queue:
#    name:
#      cancelOrder: cancelOrderQueue
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
logging:
  level:
    root: debug