spring:
  application:
    name: mall-monitor
  security: # 配置登录用户名和密码  采用spring security提供安全保障 默认情况下admin会提供 登陆页面
    user:
      name: Ryan
      password: 123456
  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}
server:
  port: 8101