server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
redis:
  database: mall
  key:
    admin: 'ums:admin'      #管理端登录用户redis缓存key前缀
  expire:
    common: 86400 # 24小时
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: test # 访问身份验证中用到用户标识
    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: macro-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀
#minio:
#  endpoint: http://192.168.6.132:9090 #MinIO服务所在地址
#  bucketName: mall #存储桶名称
#  accessKey: minioadmin #访问的key
#  secretKey: minioadmin #访问的秘钥
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 30000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 30000 #服务请求处理超时时间（毫秒）
logging:
  level:
    root: debug